"""new user fields

Revision ID: 962ffd917ee3
Revises: 
Create Date: 2024-10-26 09:14:16.896281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962ffd917ee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ig_handle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fb_handle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('twitter_handle', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('twitter_handle')
        batch_op.drop_column('fb_handle')
        batch_op.drop_column('ig_handle')
        batch_op.drop_column('name')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
